---
title: "GHA-eplot_woody_plant_stem"
output: 
  html_document:
    toc: true
---
```{r, include=FALSE}
library(lubridate)

source('D:\\Documents and Settings\\mcooper\\GitHub\\vs-data-tools\\automate_rmds\\functions.R')

pg_conf <- read.csv('D:\\Documents and Settings\\mcooper\\GitHub\\vitalsigns-data-reports\\rds_settings', stringsAsFactors=FALSE)
vs_db <- src_postgres(dbname='vitalsigns', host=pg_conf$host,
                      user=pg_conf$user, password=pg_conf$pass,
                      port=pg_conf$port)

country <- 'ALL'

data <- tbl(vs_db, 'curation__eplot_woody_plant_stem') %>% 
  data.frame

if (country != 'ALL'){
  data <- filter(data, Country==country)
}

gp_var <- get_gp_var(country)

```
Report generated `r now(tzone='UTC')` UTC. 

#Variable Summaries
##var1
```{r, echo=FALSE, warning=FALSE, messages=FALSE}
disp(data, 'Stem.height', type = 'decimal', gp_var=gp_var)

nullsd <- count_nulls(data, 'Stem.height', gp_var)
outsd <- count_outliers(data, 'Stem.height', gp_var)

kable(nullsd[[1]], col.names=nullsd[[2]])
kable(outsd[[1]], col.names=outsd[[2]])

```

##var2
```{r, echo=FALSE, warning=FALSE, messages=FALSE}
disp(data, 'Stem.width', type = 'decimal', gp_var=gp_var)

nullsd <- count_nulls(data, 'Stem.width', gp_var)
outsd <- count_outliers(data, 'Stem.width', gp_var)

kable(nullsd[[1]], col.names=nullsd[[2]])
kable(outsd[[1]], col.names=outsd[[2]])
```

##var3
```{r, echo=FALSE, warning=FALSE, messages=FALSE}
disp(data, 'Stem.circumference', type = 'decimal', gp_var=gp_var)

nullsd <- count_nulls(data, 'Stem.circumference', gp_var)
outsd <- count_outliers(data, 'Stem.circumference', gp_var)

kable(nullsd[[1]], col.names=nullsd[[2]])
kable(outsd[[1]], col.names=outsd[[2]])
```

#Raw Data
```{r, echo=FALSE, warning=FALSE}
DT::datatable(data[ ,!(names(data) %in% c('uuid', 'survey_uuid', 'parent_uuid', 'autoqa_severity'))])
```


#See Also
[TZA-eplot](../TZA-eplot.html)

[TZA-eplot_subplot_landscapefn](../TZA-eplot_subplot_landscapefn.html)

[TZA-eplot_subplot_vegetation](../TZA-eplot_subplot_vegetation.html)

[TZA-eplot_subplot_woody_canopy](../TZA-eplot_subplot_woody_canopy.html)

[TZA-eplot_woody_plant](../TZA-eplot_woody_plant.html)
