SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    t.field_id AS "Field ID",
    t.field_name AS "Field name",
    agric.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    agric.landscape_no AS "Landscape #",
    agric.hh_refno AS "Household ID",
    agric.data_entry_date AS "Data entry date",
    t.ag2a_vs_2b1,
    t.ag2a_vs_2b1_other,
    t.ag2a_vs_2b2_1,
    t.ag2a_vs_2c,
    t.ag2a_vs_2c_other,
    t.ag2a_vs_2d1,
    t.ag2a_04,
    t.ag2a_07,
    t.ag2a_08,
    t.ag2a_08_other,
    t.gps_coords,
    t.ag3a_02_1,
    t.ag3a_02_2,
    t.ag3a_02_2_1,
    t.ag2a_09,
    t.ag2a_vs_08a,
    t.ag2a_vs_8b,
    t.ag2a_vs_8c
   FROM (((agric_field_roster t
     JOIN agric ON (((t.parent_uuid)::text = (agric.uuid)::text)))
     JOIN country ON (((country.country)::text = (agric.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (agric.country)::text) AND (landscape.landscape_no = agric.landscape_no))))
