SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    agric.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    agric.landscape_no AS "Landscape #",
    agric.hh_refno AS "Household ID",
    agric.data_entry_date AS "Data entry date",
    t.field_id AS "Field ID",
    t.season AS "Season",
    t.zaocode AS "Crop ID",
    t.crop_name AS "Crop name",
    t.ag4a_01,
    t.ag4a_02,
    t.ag4a_04,
    t.ag4a_05,
    t.ag4a_05_other,
    t.ag4a_vs_5a,
    date_part('day'::text, t.ag4a_vs_5a) AS ag4a_vs_5a_day,
    date_part('month'::text, t.ag4a_vs_5a) AS ag4a_vs_5a_month,
    date_part('year'::text, t.ag4a_vs_5a) AS ag4a_vs_5a_year,
    t.ag4a_06,
    t.ag4a_08,
    t.ag4a_15,
    t.ag4a_15_unit,
    t.ag4a_16,
    t.ag4a_19,
    t.ag4a_21,
    t.ag4a_23
   FROM (((agric_crops_by_field t
     JOIN agric ON (((t.parent_uuid)::text = (agric.uuid)::text)))
     JOIN country ON (((country.country)::text = (agric.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (agric.country)::text) AND (landscape.landscape_no = agric.landscape_no))))
