SELECT agric.uuid,
    agric.survey_uuid,
    agric.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    agric.region AS "Region",
    agric.district AS "District",
    agric.landscape_no AS "Landscape #",
    agric.hh_refno AS "Household ID",
    agric.hh_head_refno AS "Household head ID",
    agric.enumerator_id AS "Enumerator ID",
    agric.time_interview_start AS "Time interview start",
    agric.date_of_interview AS "Date of interview",
    agric.supervisor_id AS "Supervisor ID",
    agric.questionnaire_inspection_date AS "Questionnaire inspection date",
    agric.clerk_id AS "Clerk ID",
    agric.data_entry_date AS "Data entry date",
    agric.fr_01,
    agric.fr2_10,
    agric.fr_5,
    agric.ag12b_vs_09a,
    agric.ag12a_vs_10,
    agric.ag12a_vs_10_other,
    agric.end_time AS "End Time",
    agric.survey_instrument AS "Survey Instrument"
   FROM ((agric
     JOIN country ON (((country.country)::text = (agric.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (agric.country)::text) AND (landscape.landscape_no = agric.landscape_no))))