SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    agric.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    agric.landscape_no AS "Landscape #",
    agric.hh_refno AS "Household ID",
    agric.data_entry_date AS "Data entry date",
    t.lvstkcode AS "Livestock code",
    t.animal_name AS "Animal name",
    t.ag10a_05_1,
    t.ag10a_05_2,
    t.ag10a_05_3,
    t.ag10a_19,
    t.ag10a_20,
    t.ag10a_21,
    t.ag10a_24,
    t.ag10a_25,
    t.ag10a_26,
    t.ag10a_27,
    t.ag10a_33,
    t.ag10a_34,
    t.ag10a_vs_01,
    t.ag10a_vs_02,
    t.ag10a_vs_03,
    t.ag10a_vs_04
   FROM (((agric_livestock t
     JOIN agric ON (((t.parent_uuid)::text = (agric.uuid)::text)))
     JOIN country ON (((country.country)::text = (agric.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (agric.country)::text) AND (landscape.landscape_no = agric.landscape_no))))