SELECT eplotsoils_processed.uuid,
    eplotsoils_processed.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplotsoils_processed.landscape_no AS "Landscape #",
    eplotsoils_processed.eplot_no AS "Eplot #",
    (((((eplotsoils_processed.country)::text || '-'::text) || eplotsoils_processed.landscape_no) || '-'::text) || eplotsoils_processed.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplotsoils_processed.sample_date AS "Sampling date",
    eplotsoils_processed.soil_depth_class AS "Sampling depth class",
    eplotsoils_processed.sample_depth_top,
    eplotsoils_processed.sample_depth_bottom,
    eplotsoils_processed.ssn AS "SSN",
    eplotsoils_processed.barcode_id,
    eplotsoils_processed.acidified_carbon AS "Carbon content for acid treated sample to remove carbonates (% ",
    eplotsoils_processed.acidified_nitrogen AS "Nitrogen content for acid treated sample to remove carbonates (",
    eplotsoils_processed.clay_icraf AS "Clay content for calgon dispersed particles-recorded after 4 mi",
    eplotsoils_processed.sand_icraf AS "Sand content for calgon dispersed particles-recorded after 4 mi",
    eplotsoils_processed.silt_icraf AS "Silt content for calgon dispersed particles-recorded after 4 mi",
    eplotsoils_processed.baseum AS "Sum of Mehlich-3 bases (Ca Mg K Na) (cmolc kg^-1)",
    eplotsoils_processed.exacidity AS "Exchangeable Acidity (cmolc kg^-1)",
    eplotsoils_processed.ec AS "Soil conductivity/ Salinity (uS/cm)",
    eplotsoils_processed.exch_al AS "Exchangeable Aluminium (meq/100g)",
    eplotsoils_processed.ph AS "Soil pH in water (soil to water ratio of 1 to 2 weight to volum",
    eplotsoils_processed.psi AS "P sorption index (Bache and Williams 1971)",
    eplotsoils_processed.clay_cnls AS "Clay content by hydrometer method (%)",
    eplotsoils_processed.sand_cnls AS "Sand content by hydrometer method (%)",
    eplotsoils_processed.silt_cnls AS "Silt content by hydrometer method (%)",
    eplotsoils_processed.total_carbon AS "Total Carbon content (% by weight)",
    eplotsoils_processed.total_nitrogen AS "Total Nitrogen content (% by weight)",
    eplotsoils_processed.m3_al AS "Exchangeable aluminium concentration by Mehlich 3 extraction (m",
    eplotsoils_processed.m3_b AS "Boron concentration by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_ca AS "Exchangeable calcium concentration by Mehlich 3 extraction (mg ",
    eplotsoils_processed.m3_cu AS "Copper concentration by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_fe AS "Iron concentration by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_k AS "Potassium concentration by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_mg AS "Exchangeable Magnesium by wet method (mg kg^-1)",
    eplotsoils_processed.m3_mn AS "Exchangeable Manganese concentration by Mehlich 3 extraction (m",
    eplotsoils_processed.m3_na AS "Exchangeable Sodium concentration by Mehlich 3 extraction (mg k",
    eplotsoils_processed.m3_p AS "Phosphorus by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_s AS "Sulphur by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.m3_zn AS "Zinc by Mehlich 3 extraction (mg kg^-1)",
    eplotsoils_processed.al AS "Aluminium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.bi AS "Bismuth total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.br AS "Bromine total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.cl AS "Chlorine total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.cu AS "Copper total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.ga AS "Gallium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.k AS "Potassium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.la AS "Lanthanum total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.mg AS "Magnesium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.na AS "Sodium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.ni AS "Nickel total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.p AS "Phosphorus total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.pb AS "Lead total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.pr AS "Praseodymium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.sc AS "Scandium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.sm AS "Samarium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.sr AS "Strontium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.ta AS "Tantalum total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.th AS "Thorium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.v AS "Vanadium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.w AS "Tungsten total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.y AS "Yttrium total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.zn AS "Zinc total element concentration TXRF (mg kg^-1)",
    eplotsoils_processed.zr AS "Zirconium total element concentration TXRF (mg kg^-1)"
   FROM ((eplotsoils_processed
     JOIN country ON (((country.country)::text = (eplotsoils_processed.country)::text)))
     JOIN ( SELECT DISTINCT ON (eplot_1.country, eplot_1.landscape_no, eplot_1.eplot_no) eplot_1.country,
            eplot_1.landscape_no,
            eplot_1.eplot_no,
            eplot_1.gpsse_lat,
            eplot_1.gpsse_long,
            eplot_1.gpssw_lat,
            eplot_1.gpssw_long,
            eplot_1.gpsne_lat,
            eplot_1.gpsne_long,
            eplot_1.gpsnw_lat,
            eplot_1.gpsnw_long
           FROM eplot eplot_1) eplot ON (((((eplotsoils_processed.country)::text = (eplot.country)::text) AND (eplotsoils_processed.landscape_no = eplot.landscape_no)) AND (eplotsoils_processed.eplot_no = eplot.eplot_no))))