SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    eplot.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplot.landscape_no AS "Landscape #",
    eplot.eplot_no AS "Eplot #",
    (((((eplot.country)::text || '-'::text) || eplot.landscape_no) || '-'::text) || eplot.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplot.date AS "Date",
    t.subplot AS "Subplot #",
    t.rooted AS "Rooted Plants",
    t.litter AS "Litter Cover",
    t.downed AS "Downed Wood",
    t.stone AS "Stone or Gravel",
    t.dung AS "Dung",
    t.disturbed AS "Disturbed Soil",
    t.porous AS "Undisturbed Bare & Porous Soil",
    t.sealed AS "Undisturbed but Sealed Soil",
    t.sodic AS "Sodic Soil",
    t.crust AS "Microfloral Crust",
    t.termite AS "Termite Mound",
    t.herbaceous AS "Herbaceous Crown Cover Score",
    t.herbaceous_erosion AS "Soil Erosion Score"
   FROM ((eplot_subplot_landscapefn t
     JOIN eplot ON (((t.parent_uuid)::text = (eplot.uuid)::text)))
     JOIN country ON (((country.country)::text = (eplot.country)::text)))
