SELECT eplot.uuid,
    eplot.survey_uuid,
    eplot.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplot.landscape_no AS "Landscape #",
    eplot.eplot_no AS "Eplot #",
    (((((eplot.country)::text || '-'::text) || eplot.landscape_no) || '-'::text) || eplot.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplot.date AS "Date",
    eplot.measurer1_id AS "Measurer #1",
    eplot.measurer1_first_name AS "Measurer #1 first",
    eplot.measurer1_last_name AS "Measurer #1 last",
    eplot.measurer2_id AS "Measurer #2",
    eplot.measurer2_first_name AS "Measurer #2 first",
    eplot.measurer2_last_name AS "Measurer #2 last",
    eplot.scribe_id AS "Scribe",
    eplot.scribe_first_name AS "Scribe first",
    eplot.scribe_last_name AS "Scribe last",
    eplot.manager_id AS "Manager",
    eplot.manager_first_name AS "Manager first",
    eplot.manager_last_name AS "Manager last",
    eplot.radius AS "Subplot Radius",
    eplot.gpsne_accuracy AS "GPS NE accuracy",
    eplot.gpsne_lat AS "GPS NE latitude",
    eplot.gpsne_long AS "GPS NE longitude",
    eplot.gpsnw_accuracy AS "GPS NW accuracy",
    eplot.gpsnw_lat AS "GPS NW latitude",
    eplot.gpsnw_long AS "GPS NW longitude",
    eplot.gpsse_accuracy AS "GPS SE accuracy",
    eplot.gpsse_lat AS "GPS SE latitude",
    eplot.gpsse_long AS "GPS SE longitude",
    eplot.gpssw_accuracy AS "GPS SW accuracy",
    eplot.gpssw_lat AS "GPS SW latitude",
    eplot.gpssw_long AS "GPS SW longitude",
    eplot.gpsse_start AS "GPS NE start time",
    eplot.gpsse_end AS "GPS NE end time",
    eplot.photo_e AS "Photo E",
    eplot.photo_n AS "Photo N",
    eplot.photo_s AS "Photo S",
    eplot.photo_w AS "Photo W",
    eplot.observations AS "Observations"
   FROM (eplot
     JOIN country ON (((country.country)::text = (eplot.country)::text)))
