SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    eplot.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplot.landscape_no AS "Landscape #",
    eplot.eplot_no AS "Eplot #",
    (((((eplot.country)::text || '-'::text) || eplot.landscape_no) || '-'::text) || eplot.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplot.date AS "Date",
    t.subplot AS "Subplot #",
    t.basal_circ_height AS "Basal circumference measurement height",
    t.tree_code,
    t.tree_tax AS "Tree species",
    ps.genus AS "Genus",
    ps.species AS "Species",
    ps.subspecies AS "Subspecies",
    ps.common AS "Common Name",
    t.tree_stems_class AS "Tree stems type",
    t.tree_multistem_samesize_numstems AS "Identical stems count",
    t.tree_multistem_numstems AS "Different stems count",
    t.tree_singlestem_canopy_width AS "Single stem canopy width",
    t.tree_singlestem_height AS "Single stem height",
    t.tree_singlestem_circumference AS "Single stem circumference",
    t.tree_multistem_samesize_canopy_width AS "Canopy width of multiple identical stems",
    t.tree_multistem_samesize_circumference AS "Circumference of multiple identical stems",
    t.tree_multistem_samesize_height AS "Height of multiple identical stems",
    t.tree_photo AS "Photo of whole tree",
    t.tree_stembark_photo AS "Photo of stem and bark",
    t.tree_branch_photo AS "Photo of a branch",
    t.tree_leaf_photo AS "Photo of a leaf"
   FROM (((eplot_woody_plant t
     JOIN eplot ON (((t.survey_uuid)::text = (eplot.uuid)::text)))
     LEFT JOIN plant_species ps ON ((ps.id = t.tree_tax)))
     JOIN country ON (((country.country)::text = (eplot.country)::text)))
