SELECT t.uuid,
    t.parent_uuid,
    t.survey_uuid,
    eplot.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplot.landscape_no AS "Landscape #",
    eplot.eplot_no AS "Eplot #",
    (((((eplot.country)::text || '-'::text) || eplot.landscape_no) || '-'::text) || eplot.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplot.date AS "Date",
    t.subplot AS "Subplot #",
    t.mass AS "Herbaceous Mass Score",
    t.rank1_tax AS "Plant Species Ranked 1",
    ps1.genus AS "Genus Ranked 1",
    ps1.species AS "Species Ranked 1",
    ps1.subspecies AS "Subspecies Ranked 1",
    ps1.common AS "Common Name Ranked 1",
    t.rank1_tree_photo AS "Species Ranked 1 - Photo of whole plant",
    t.rank1_stembark_photo AS "Species Ranked 1 - Photo of stem & bark",
    t.rank1_branch_photo AS "Species Ranked 1 - Photo of a branch",
    t.rank1_leaf_photo AS "Species Ranked 1 - Photo of a leaf",
    t.rank2_tax AS "Plant Species Ranked 2",
    ps2.genus AS "Genus Ranked 2",
    ps2.species AS "Species Ranked 2",
    ps2.subspecies AS "Subspecies Ranked 2",
    ps2.common AS "Common Name Ranked 2",
    t.rank2_tree_photo AS "Species Ranked 2 - Photo of whole plant",
    t.rank2_stembark_photo AS "Species Ranked 2 - Photo of stem & bark",
    t.rank2_branch_photo AS "Species Ranked 2 - Photo of a branch",
    t.rank2_leaf_photo AS "Species Ranked 2 - Photo of a leaf",
    t.rank3_tax AS "Plant Species Ranked 3",
    ps3.genus AS "Genus Ranked 3",
    ps3.species AS "Species Ranked 3",
    ps3.subspecies AS "Subspecies Ranked 3",
    ps3.common AS "Common Name Ranked 3",
    t.rank3_tree_photo AS "Species Ranked 3 - Photo of whole plant",
    t.rank3_stembark_photo AS "Species Ranked 3 - Photo of stem & bark",
    t.rank3_branch_photo AS "Species Ranked 3 - Photo of a branch",
    t.rank3_leaf_photo AS "Species Ranked 3 - Photo of a leaf"
   FROM (((((eplot_subplot_vegetation t
     JOIN eplot ON (((t.parent_uuid)::text = (eplot.uuid)::text)))
     LEFT JOIN plant_species ps1 ON ((ps1.id = t.rank1_tax)))
     LEFT JOIN plant_species ps2 ON ((ps2.id = t.rank2_tax)))
     LEFT JOIN plant_species ps3 ON ((ps3.id = t.rank3_tax)))
     JOIN country ON (((country.country)::text = (eplot.country)::text)))