SELECT eplotsoils_sample.uuid,
    eplotsoils_sample.survey_uuid,
    eplotsoils_sample.country AS "Country",
    country.partner_institution AS "Partner Organization",
    eplotsoils_sample.landscape_no AS "Landscape #",
    eplotsoils_sample.eplot_no AS "Eplot #",
    (((((eplotsoils_sample.country)::text || '-'::text) || eplotsoils_sample.landscape_no) || '-'::text) || eplotsoils_sample.eplot_no) AS "Eplot Code",
    eplot.gpsne_lat AS latitude,
    eplot.gpsne_long AS longitude,
    eplotsoils_sample.sampler_id AS "Sampler",
    eplotsoils_sample.sampler_first_name,
    eplotsoils_sample.sampler_last_name,
    eplotsoils_sample.scribe_id AS "Scribe",
    eplotsoils_sample.scribe_first_name,
    eplotsoils_sample.scribe_last_name,
    eplotsoils_sample.sample_date AS "Sampling date",
    eplotsoils_sample.se_top_restriction_depth AS "Depth to top sampling restriction (SE cm)",
    eplotsoils_sample.se_subsoil_restriction_depth AS "Depth to subsoil sampling restriction (SE cm)",
    eplotsoils_sample.se_50_80_restriction_depth AS "Depth to 50-80 sampling restriction (SE cm)",
    eplotsoils_sample.se_80_100_restriction_depth AS "Depth to 80-100 sampling restriction (SE cm)",
    eplotsoils_sample.ne_top_restriction_depth AS "Depth to top sampling restriction (NE cm)",
    eplotsoils_sample.ne_sub_restriction_depth AS "Depth to subsoil sampling restriction (NE cm)",
    eplotsoils_sample.nw_top_restriction_depth AS "Depth to top sampling restriction (NW cm)",
    eplotsoils_sample.nw_sub_restriction_depth AS "Depth to subsoil sampling restriction (NW cm)",
    eplotsoils_sample.sw_top_restriction_depth AS "Depth to top sampling restriction (SW cm)",
    eplotsoils_sample.sw_sub_restriction_depth AS "Depth to subsoil sampling restriction (SW cm)",
    eplotsoils_sample.se_50_80_texture AS "Hand texture of SE 50-80 sample",
    eplotsoils_sample.se_80_100_texture AS "Hand texture of SE 80-100 sample",
    eplotsoils_sample.composite_top_texture AS "Composite top sample texture",
    eplotsoils_sample.composite_subsoil_texture AS "Composite subsoil sample texture",
    eplotsoils_sample.se_top_texture,
    eplotsoils_sample.se_subsoil_texture,
    eplotsoils_sample.ne_top_texture,
    eplotsoils_sample.ne_sub_texture,
    eplotsoils_sample.nw_top_texture,
    eplotsoils_sample.nw_sub_texture,
    eplotsoils_sample.sw_top_texture,
    eplotsoils_sample.sw_sub_texture,
    eplotsoils_sample.survey_instrument,
    eplotsoils_sample.se_top_barcode,
    eplotsoils_sample.se_subsoil_barcode,
    eplotsoils_sample.se_50_80_barcode,
    eplotsoils_sample.se_80_100_barcode
   FROM ((eplotsoils_sample
     JOIN country ON (((country.country)::text = (eplotsoils_sample.country)::text)))
     JOIN ( SELECT DISTINCT ON (eplot_1.country, eplot_1.landscape_no, eplot_1.eplot_no) eplot_1.country,
            eplot_1.landscape_no,
            eplot_1.eplot_no,
            eplot_1.gpsse_lat,
            eplot_1.gpsse_long,
            eplot_1.gpssw_lat,
            eplot_1.gpssw_long,
            eplot_1.gpsne_lat,
            eplot_1.gpsne_long,
            eplot_1.gpsnw_lat,
            eplot_1.gpsnw_long
           FROM eplot eplot_1) eplot ON (((((eplotsoils_sample.country)::text = (eplot.country)::text) AND (eplotsoils_sample.landscape_no = eplot.landscape_no)) AND (eplotsoils_sample.eplot_no = eplot.eplot_no))))
