SELECT farmfieldsoils_processed.uuid,
    farmfieldsoils_processed.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    farmfieldsoils_processed.landscape_no AS "Landscape #",
    farmfieldsoils_processed.hh_refno AS "Household ID",
    farmfieldsoils_processed.field_no AS "Field #",
    farmfieldsoils_processed.sample_date AS "Sampling date",
    farmfieldsoils_processed.soil_depth_class AS "Sampling depth class",
    farmfieldsoils_processed.sample_depth_top,
    farmfieldsoils_processed.sample_depth_bottom,
    farmfieldsoils_processed.ssn AS "SSN",
    farmfieldsoils_processed.acidified_carbon AS "Carbon content for acid treated sample to remove carbonates (% ",
    farmfieldsoils_processed.acidified_nitrogen AS "Nitrogen content for acid treated sample to remove carbonates (",
    farmfieldsoils_processed.clay_cnls AS "Clay content by hydrometer method (%)",
    farmfieldsoils_processed.clay_icraf AS "Clay content for calgon dispersed particles-recorded after 4 mi",
    farmfieldsoils_processed.baseum AS "Sum of Mehlich-3 bases (Ca Mg K Na) (cmolc kg^-1)",
    farmfieldsoils_processed.exacidity AS "Exchangeable Acidity (cmolc kg^-1)",
    farmfieldsoils_processed.ec AS "Soil conductivity/ Salinity (uS/cm)",
    farmfieldsoils_processed.exch_al AS "Exchangeable Aluminium (meq/100g)",
    farmfieldsoils_processed.ph AS "Soil pH in water (soil to water ratio of 1 to 2 weight to volum",
    farmfieldsoils_processed.psi AS "P sorption index (Bache and Williams 1971)",
    farmfieldsoils_processed.sand_cnls AS "Sand content by hydrometer method (%)",
    farmfieldsoils_processed.sand_icraf AS "Sand content for calgon dispersed particles-recorded after 4 mi",
    farmfieldsoils_processed.silt_cnls AS "Silt content by hydrometer method (%)",
    farmfieldsoils_processed.silt_icraf AS "Silt content for calgon dispersed particles-recorded after 4 mi",
    farmfieldsoils_processed.total_carbon AS "Total Carbon content (% by weight)",
    farmfieldsoils_processed.total_nitrogen AS "Total Nitrogen content (% by weight)",
    farmfieldsoils_processed.m3_al AS "Exchangeable aluminium concentration by Mehlich 3 extraction (m",
    farmfieldsoils_processed.m3_b AS "Boron concentration by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_ca AS "Exchangeable calcium concentration by Mehlich 3 extraction (mg ",
    farmfieldsoils_processed.m3_cu AS "Copper concentration by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_fe AS "Iron concentration by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_k AS "Potassium concentration by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_mg AS "Exchangeable Magnesium by wet method (mg kg^-1)",
    farmfieldsoils_processed.m3_mn AS "Exchangeable Manganese concentration by Mehlich 3 extraction (m",
    farmfieldsoils_processed.m3_na AS "Exchangeable Sodium concentration by Mehlich 3 extraction (mg k",
    farmfieldsoils_processed.m3_p AS "Phosphorus by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_s AS "Sulphur by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.m3_zn AS "Zinc by Mehlich 3 extraction (mg kg^-1)",
    farmfieldsoils_processed.al AS "Aluminium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.bi AS "Bismuth total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.br AS "Bromine total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.cl AS "Chlorine total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.cu AS "Copper total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.ga AS "Gallium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.k AS "Potassium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.la AS "Lanthanum total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.mg AS "Magnesium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.na AS "Sodium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.ni AS "Nickel total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.p AS "Phosphorus total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.pb AS "Lead total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.pr AS "Praseodymium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.sc AS "Scandium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.sm AS "Samarium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.sr AS "Strontium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.ta AS "Tantalum total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.th AS "Thorium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.v AS "Vanadium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.w AS "Tungsten total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.y AS "Yttrium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.zn AS "Zinc total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.zr AS "Zirconium total element concentration TXRF (mg kg^-1)",
    farmfieldsoils_processed.barcode_id AS "Barcode ID"
   FROM ((farmfieldsoils_processed
     JOIN country ON (((country.country)::text = (farmfieldsoils_processed.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (farmfieldsoils_processed.country)::text) AND (landscape.landscape_no = farmfieldsoils_processed.landscape_no))))