SELECT t.uuid,
    t.survey_uuid,
    t.parent_uuid,
    hh.country AS "Country",
    country.partner_institution AS "Partner Organization",
    landscape.centerpoint_longitude AS longitude,
    landscape.centerpoint_latitude AS latitude,
    hh.landscape_no AS "Landscape #",
    hh.hh_refno AS "Household ID",
    hh.data_entry_date AS "Data entry date",
    t.hh_j01,
    t.hh_j02,
    t.hh_j02oth,
    t.hh_j03,
    t.hh_j04_1,
    t.hh_j04_2,
    t.hh_j05,
    t.hh_j05_other,
    t.hh_j06,
    t.hh_j06_other,
    t.hh_j07,
    t.hh_j07_other,
    t.hh_j08,
    t.hh_j08_other,
    t.hh_j09,
    t.hh_j09_other,
    t.hh_j10,
    t.hh_j11,
    t.hh_j11_other,
    t.hh_j12,
    t.hh_j12_other,
    t.hh_j13,
    t.hh_j13_other,
    t.hh_j14,
    t.hh_j14_oth,
    t.hh_j15,
    t.hh_j15_oth,
    t.hh_j16_1,
    t.hh_j16_2,
    t.hh_j16_1oth,
    t.hh_j16_2oth,
    t.hh_j17_1,
    t.hh_j17_2,
    t.hh_j17_1oth,
    t.hh_j17_2oth,
    t.hh_j18_1,
    t.hh_j18_2,
    t.hh_j18_1oth,
    t.hh_j18_2oth,
    t.hh_j19_1,
    t.hh_j19_2,
    t.hh_j19_1oth,
    t.hh_j19_2oth,
    t.hh_j20
   FROM ((("household_secJ1" t
     JOIN household hh ON (((t.parent_uuid)::text = (hh.uuid)::text)))
     JOIN country ON (((country.country)::text = (hh.country)::text)))
     JOIN landscape ON ((((landscape.country)::text = (hh.country)::text) AND (landscape.landscape_no = hh.landscape_no))))