SELECT rapid_water.uuid,
    rapid_water.survey_uuid,
    rapid_water.country AS "Country",
    country.partner_institution AS "Partner Organization",
    rapid_water.landscape_no AS "Landscape Number",
    rapid_water.vs_code AS "VS Code",
    rapid_water.rapid_water_asses_no AS "Rapid Water Assessment #",
    rapid_water.water_sample_no AS "Water Sample #",
    rapid_water.rapid_water_asses_date AS "Assessment Date",
    rapid_water.observer_id AS "Observer",
    rapid_water.observer_first_name AS "Observer First Name",
    rapid_water.observer_last_name AS "Observer Last Name",
    rapid_water.gpsnw_lat AS latitude,
    rapid_water.gpsnw_long AS longitude,
    rapid_water.gpsnw_accuracy AS "GPS Accuracy",
    rapid_water.photo_file_name AS "Photo File Name",
    rapid_water.photo_water AS "Photo of Marker",
    rapid_water.water_depth_marker AS "Water Depth against Marker",
    rapid_water.b_14_1 AS "Open Water Score (1-10)",
    rapid_water.b_14_2 AS "Algal Score (1-10)",
    rapid_water.b_14_3 AS "Aquatic Plants Score (1-10)",
    rapid_water.b_14_4 AS "Exotic Weeds Score (1-10)",
    rapid_water.b_14_5 AS "Litter Score (1-10)",
    rapid_water.b_14_6 AS "Foam Score (1-10)",
    rapid_water.b_14_7 AS "Oily/Metallic Sheen Score (1-10)",
    rapid_water.dp_color_type AS "Color Type",
    rapid_water.dp_color_intensity AS "Color Intensity",
    rapid_water.dp_smell_desc AS "Smell Description",
    rapid_water.dp_smell_intensity AS "Smell Intensity",
    rapid_water.dp_taste AS "Taste Description",
    rapid_water.dp_taste_intensity AS "Taste Intensity",
    rapid_water.dp_obs_use AS "Observed Uses",
    rapid_water.dp_obs_use_drinking AS "Used for Drinking",
    rapid_water.dp_obs_use_bathing AS "Used for Bathing",
    rapid_water.dp_obs_use_livestock AS "Used for Livestock",
    rapid_water.dp_obs_use_washing AS "Used for Washing",
    rapid_water.dp_obs_use_irrigation AS "Used for Irrigation",
    rapid_water.dp_obs_use_mining AS "Used for Mining",
    rapid_water.survey_instrument AS "Survey Instrument"
   FROM (rapid_water
     JOIN country ON (((country.country)::text = (rapid_water.country)::text)))