SELECT rra.uuid,
    rra.survey_uuid,
    rra.country AS "Country",
    country.partner_institution AS "Partner Organization",
    rra.rapid_road_asses_no AS "Rapid Road Assessment #",
    rra.date AS "Date",
    rra.avg_height_upper_canopy AS "Average height of upper canopy",
    rra.canopy1 AS "Pct contrib of height class to total proj cano cover (<1m)",
    rra.canopy2 AS "Pct contrib of height class to total proj cano cover (1-2m)",
    rra.canopy3 AS "Pct contrib of height class to total proj cano cover (2-5m)",
    rra.canopy4 AS "Pct contrib of height class to total proj cano cover (5-20m)",
    rra.canopy5 AS "Pct contrib of height class to total proj cano cover (>20m)",
    rra.observer_id AS "Observer",
    rra.observer_first_name,
    rra.observer_last_name,
    rra.gps_start AS "GPS measurement start time",
    rra.gps_end AS "GPS measurement end time",
    rra.gps_lat AS latitude,
    rra.gps_long AS longitude,
    rra.gps_accuracy AS "GPS accuracy",
    rra.gps_measurement_counts AS "GPS Measurement Counts",
    rra.mark1 AS "Distance from marker (km)",
    rra.mark2 AS "Name of marker",
    rra.mark3 AS "Next closest town on route",
    rra.pan_or_many AS "Panorama or four pictures?",
    rra.panorama AS "Panorama photo",
    rra.photo_n AS "Photo facing North",
    rra.photo_e AS "Photo facing East",
    rra.photo_s AS "Photo facing South",
    rra.photo_w AS "Photo facing West",
    rra.treeshrub_projected_cover AS "Tree / shrub total projected canopy cover",
    rra.use_protected AS "Protected use",
    rra.use_livestock AS "Livestock grazing use",
    rra.use_wood AS "Wood harvesting use",
    rra.use_short_crop AS "Short duration cropping use",
    rra.use_tree_crops AS "Tree crops use",
    rra.use_hab_biz AS "Habitation / business use",
    rra.survey_instrument AS "Survey Instrument"
   FROM (rra
     JOIN country ON (((country.country)::text = (rra.country)::text)))